name: Call a reusable workflow

on:
  push:

jobs:
  call-workflow-a:
    uses: jpveooys/github-actions-reuse-testing/.github/workflows/reuse-a.yml@main
    with:
      username: Mona

  call-workflow-b:
    uses: jpveooys/github-actions-reuse-testing/.github/workflows/reuse-b.yml@main
    with:
      username: Bart
